### ISSUE TITLE
Изменить названия проектов

### ISSUE THREAD

**Issue by MikhailMasny** [securedevteam/Payment-Platform#17]
Необходимо привести проекты ко следующему стилю: 
- *.API.*
- *.определенное название.*

(?) Перевести инициализацию БД в монолитный проект.

**Comment by MikhailMasny** [comment]
@s207883 что скажешь?

**Comment by s207883** [comment]
Скажу что до меня не дошло

**Comment by MikhailMasny** [comment]
Принято не изменять названия проектов.
